---
galaxy_info:
  author: Bert Van Vreckem
  description: Installs collectd and, optionally, collectd-web on RHEL/CentOS 7
  license: BSD
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
      - 7
  categories:
    - networking
    - monitoring
dependencies: []
