# roles/collectd/defaults/main.yml
# Role variables that may be changed by the administrator
---

collectd_interval: 10
collectd_timeout: 2
collectd_read_threads: 5
collectd_write_threads: 5

collectd_log_level: info

collectd_web_enabled: true
